[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/auth"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/auth/*"
  to = "/"
  status = 302
  force = true

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
